### ISSUE TITLE
Support of build process on SLES 11 SP3

### ISSUE THREAD

**Issue by psytester** [BeID-lab/eIDClientCore#31]
While it is possible to build the eIDClientCore on actual openSUSE, I need a build system which fits into given environment on SLES 11 SP3 host.

Original autoconf 2.63 and gcc-c++ 4.3 from SLES repository is too old to build the project, but I managed to install autoconf 2.69 and gcc-c++ 4.9 and its dependencies based on packages from http://software.opensuse.org

With make I can build all steps expect the last one "eIDClient" :-(
I'm not the expert for auto-tools, but make job has build cryptopp and this cryptopp contains the include header files, etc...
Do I really need to install libcryptopp-devel if I compile it from sources?
While compiling eIDClient it stops because Header files from cryptopp where not found (due to missing libcryptopp-devel package?)
The autoconf created Makefile does not set the CRYPTOPP_CFLAG and CRYPTOPP_LIBS to the Location of cryptopp sources and compiled results

**Comment by frankmorgner** [comment]
Using SUSE's Crypto++ packages instead of compiling it by hand is an option (as stated in Readme.md), it is not mandatory. https://github.com/BeID-lab/eIDClientCore/blob/master/Makefile does not require you to install any package except the base components for building the project and fetching the sources... In this Makefile `pkg-config` is used for determining the Crypto++ parameters (https://github.com/BeID-lab/eIDClientCore/blob/master/Makefile#L90).

An other possibility is to work around `pkg-config` by using `./configure CRYPTOPP_CFLAG=... CRYPTOPP_LIBS=...` for passing your custom parameters.

If you still have trouble, please give post `config.log`.

**Comment by psytester** [comment]
I have added to the Makefile in section of calling eIDClient "./configure" those two entries and it works now:
..... 
CRYPTOPP_CFLAGS=-I$(PREFIX)/include:$(PREFIX)/cryptopp \
CRYPTOPP_LIBS="-lcryptopp" \
....

**Comment by frankmorgner** [comment]
I would change it to `... CRYPTOPP_LIBS="-L$(PREFIX)/lib -lcryptopp"`, but your suggestion is reasonable, thanks for coming back to this issue.

Please have in mind that we can't modify the Makefile to generally cover any OS out there. Other projects have tried to and failed badly. The Makefile only covers what should work on most system. However, we already know that it doesn't work out of the box on Mac OS X or in a cross compiling environment though both has been tested already.

**Comment by psytester** [comment]
Cleanup...
This issue was already solved in April by #33
